### ISSUE TITLE
Looking for help in setting up Coverage service on FHIR

### ISSUE THREAD

**Issue by ranadheercp** [Asymmetrik/node-fhir-server-mongo#101]
### Do you want to request a feature, improve documentation, or ask a question?
Ask a Question
### Are you reporting a bug?
No
**What is the current behavior?**
I have a requirement to use a FHIR server to expose Coverage resource. I have come across this implementation of fhir server. I was able to setup the fhir server on my machine and test Patient service. 
However, there is no service for Coverage. 
Could someone tell me how can i generate/create the coverage service using this node-fhir-server-mongo?
**What is the expected behavior?**

**What are the steps to reproduce?**

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**

**Comment by luan-dev** [comment]
This repo is only a starter repo base off of the [@asymmetrik/node-fhir-server-core](https://github.com/Asymmetrik/node-fhir-server-core) library. There is a guide on implementing your own service there: https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/ConfiguringProfiles.md
