### ISSUE TITLE
Search query does not work properly.

### ISSUE THREAD

**Issue by ryumtym** [Asymmetrik/node-fhir-server-mongo#126]
### Do you want to request a feature, improve documentation, or ask a question?
Ask a question

### Are you reporting a bug?
Probably

**What is the current behavior?**
Search query does not work properly.

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
os: win10
node.js: 14.18.0
node-fhir-server-core: currentRelease
node-fhir-server-mongo: currentRelease

<br>
First of all, this repository is working mostly fine, thanks for creating it.

For example, if I enter `https://hapi.fhir.org/baseR4/Observation?patient=1552328` in hapifhir, I get the observation data with a patient ID of 1552328.
If I put the temporary data into node-fhir-server-mongo and do a `http://myAddress/Observation?patient=1552328` search as in hapifhir, it does not work.
But I can get the data with `http://myAddress/Observation?subject=1552328`.

[This page](https://www.hl7.org/fhir/observation.html#search) published by hl7 writes that there are 4 types of reference (group,device,patient,location) in the subject.

I think querying with [?subject=1552328] is not correct, is this a bug?

**Comment by luan-dev** [comment]
Hi @ryumtym!

The repository is not meant to be a starter and not a complete product. You must implement the [`observation.service.js`](https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/services/observation/observation.service.js) search functionality to fit your own implementation. There should be `TODO` stubs to help you out.

Please let me know if you need any help with that

**Comment by ryumtym** [comment]
Thank you for your reply.

I used observation as an example, but the same problem occurs with patient.

Also, all these problems are related to the`referenceQuerybuilder function` in [`src\querybuilder.util.js`](https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/utils/querybuilder.util.js#L109).

For example, if the value `patient/1234` is stored in `observation.subject.reference` (JSON path), it seems that the value is automatically split with a slash and only 1234 is given to argument 1 (target).

I don't think I can find any behavior in node-fhir-server-mongo regarding the splitting of the value and passing it to the argument, where is this being handled?

**Comment by luan-dev** [comment]
If I am understanding correctly, your `observation.subject.reference` is a reference to a Patient object.
This patient object's value is `patient/1234` however, the `referenceQuerybuilder` is parsing out `patient` and only leaving the `1234` as the value.
So in your code `observation.subject.reference = 1234`, but you want `observation.subject.reference = patient/1234`?
