### ISSUE TITLE
Clean npm or yarn install does not run

### ISSUE THREAD

**Issue by KevinDufendach** [Asymmetrik/node-fhir-server-mongo#131]
**What is the current behavior?**

A clean installation (removing lock file) and running `npm` or `yarn install` results in an error.

**What is the expected behavior?**

Expect to be able to do a clean installation with current dependencies.

**What are the steps to reproduce?**

``` bash
git clone https://github.com/Asymmetrik/node-fhir-server-mongo.git
cd node-fhir-server-mongo
```

Plus either

``` bash
npm install
npm run start
```

OR

``` bash
rm yarn.lock
yarn install
yarn start
```

Yields

```
option auto_reconnect is not supported
mongodb://localhost
error Command failed with exit code 1.
```

Updating config.js to remove the `auto_reconnect: true` from line 12 allows the application to run, but search queries are no longer valid. e.g.: `GET http://{{host}}:{{port}}/4_0_0/Patient?_id={{id}}`

``` json
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "internal",
            "details": {
                "text": "Unexpected: Argument \"options\" must not be function"
            }
        }
    ]
}
```

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**

OS: Windows/PwerShell
Node: v16.15.1
@asymmetrik/node-fhir-server-mongo: 2.0.0
(Pulls @asymmetrik/node-fhir-server-core: 2.2.4)

**Comment by KevinDufendach** [comment]
I've created a fix for the patient service, shown here: https://github.com/KevinDufendach/node-fhir-server-mongo/commit/54ecb97ea9ed78886c54937b3a7aa6d301bcb503

I didn't create a pull request yet, because I suspect the clean installation breaks the other services.

**Comment by luan-dev** [comment]
Sorry for the late response. We have updated the deps so if you were interested in trying again. Please reopen this issue
