### ISSUE TITLE
Passing date parameters to patient resource throws error

### ISSUE THREAD

**Issue by Fdawgs** [Asymmetrik/node-fhir-server-mongo#24]
### Do you want to request a feature, improve documentation, or ask a question?
N/A
### Are you reporting a bug?
Yes

**What is the current behavior?**

Error thrown: `error: message=date.match is not a function, stack=TypeError: date.match is not a function`

**What is the expected behavior?**
Patient resources that match the date in the birthdate parameter are returned.

**What are the steps to reproduce?**
Send the following request to the server:

```
GET /3_0_1/Patient?birthdate=1980-01-01 HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/fhir+json
Cache-Control: no-cache
```

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
Windows 10 - 64-bit, version 1607

**Comment by Robert-W** [comment]
Thanks for reporting this @FSmithYDH.

When I was briefly reading through the source code for query building utils I can see why the error is happening. This will be an easy fix. I'll start working on a patch soon and add some unit tests so this kind of thing does not happen again in the future.

**Comment by Robert-W** [comment]
Ok, so we have a patch for this. This patch will fix the issue for now but I am eventually going to clean this function up. The cleanup will be a slightly larger effort so that won't make it here immediately, but the patch should be in by EOD today.

**Comment by Robert-W** [comment]
Hey @FSmithYDH, just wanted to provide an update on this. While we were cleaning things up we re-evaluated the parameter parsing in the core library and decided on making a big change there. @jonterrylee is out today but I will check with him to see what we want to do with this.

Currently core cannot support modifiers, so field modifiers like `gender:not` and value modifiers like `lt2010-10-10`, are not possible. But we will be adding support for these soon.

**Comment by sshah-asymmetrik** [comment]
This issue was resolved with the addition of `@asymmetrik/fhir-qb-mongo`.
