### ISSUE TITLE
Initial insert of Organization resource throws path error

### ISSUE THREAD

**Issue by FSmithYDH** [Asymmetrik/node-fhir-server-mongo#26]
### Are you reporting a bug?

Yes

**What is the current behavior?**
Throws the following error:
```
error:  message=The "path" argument must be of type string. Received type object, stack=TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must
be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at Object.handleUpdateResponse (C:\Users\[username]\Documents\Projects\node-fhir-server-mongo\node_modules\@asymmetrik\node-fhir-server-core\src\server\utils\response.utils.js:152:39)
    at service.update.then (C:\Users\[username]\Documents\Projects\node-fhir-server-mongo\node_modules\@asymmetrik\node-fhir-server-core\src\server\profiles\organization\organization.controller.js:139:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The fhir database, Organization collection, and a corresponding document is still created even with this error thrown. 

Rerunning the same PUT request does not throw an error after that initial one.

**What is the expected behavior?**

An error is not thrown.

**What are the steps to reproduce?**

Send the following PUT request to a new instance of the server which has had no prior requests made to it:

```
PUT /3_0_1/Organization/f001 HTTP/1.1
Host: 127.0.0.1:3000
Cache-Control: no-cache
Content-Type: application/fhir+json

{
  "resourceType": "Organization",
  "id": "f001",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: f001</p><p><b>identifier</b>: 91654 (OFFICIAL), 17-0112278 (USUAL)</p><p><b>type</b>: University Medical Hospital <span>(Details : {urn:oid:2.16.840.1.113883.2.4.15.1060 code 'V6' = 'V6', given as 'University Medical Hospital'}; {http://hl7.org/fhir/organization-type code 'prov' = 'Healthcare Provider', given as 'Healthcare Provider'})</span></p><p><b>name</b>: Burgers University Medical Center</p><p><b>telecom</b>: ph: 022-655 2300(WORK)</p><p><b>address</b>: </p><ul><li>Galapagosweg 91 Den Burg 9105 PZ NLD (WORK)</li><li>PO Box 2311 Den Burg 9100 AA NLD (WORK)</li></ul><blockquote><p><b>contact</b></p><p><b>purpose</b>: Press <span>(Details : {http://hl7.org/fhir/contactentity-type code 'PRESS' = 'Press)</span></p><p><b>telecom</b>: ph: 022-655 2334</p></blockquote><blockquote><p><b>contact</b></p><p><b>purpose</b>: Patient <span>(Details : {http://hl7.org/fhir/contactentity-type code 'PATINF' = 'Patient)</span></p><p><b>telecom</b>: ph: 022-655 2335</p></blockquote></div>"
  },
  "identifier": [
    {
      "use": "official",
      "system": "urn:oid:2.16.528.1",
      "value": "91654"
    },
    {
      "use": "usual",
      "system": "urn:oid:2.16.840.1.113883.2.4.6.1",
      "value": "17-0112278"
    }
  ],
  "type": [
    {
      "coding": [
        {
          "system": "urn:oid:2.16.840.1.113883.2.4.15.1060",
          "code": "V6",
          "display": "University Medical Hospital"
        },
        {
          "system": "http://hl7.org/fhir/organization-type",
          "code": "prov",
          "display": "Healthcare Provider"
        }
      ]
    }
  ],
  "name": "Burgers University Medical Center",
  "telecom": [
    {
      "system": "phone",
      "value": "022-655 2300",
      "use": "work"
    }
  ],
  "address": [
    {
      "use": "work",
      "line": [
        "Galapagosweg 91"
      ],
      "city": "Den Burg",
      "postalCode": "9105 PZ",
      "country": "NLD"
    },
    {
      "use": "work",
      "line": [
        "PO Box 2311"
      ],
      "city": "Den Burg",
      "postalCode": "9100 AA",
      "country": "NLD"
    }
  ],
  "contact": [
    {
      "purpose": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/contactentity-type",
            "code": "PRESS"
          }
        ]
      },
      "telecom": [
        {
          "system": "phone",
          "value": "022-655 2334"
        }
      ]
    },
    {
      "purpose": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/contactentity-type",
            "code": "PATINF"
          }
        ]
      },
      "telecom": [
        {
          "system": "phone",
          "value": "022-655 2335"
        }
      ]
    }
  ]
}
```

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**

OS version: Windows 10 64-bit
Node.js  version: 10.11.0

**Comment by jonterrylee** [comment]
@FSmithYDH 

Which branch of the Core lib are you using?  

In the package.json ("@asymmetrik/node-fhir-server-core": "git+https://github.com/Asymmetrik/node-fhir-server-core.git,)

**Comment by jonterrylee** [comment]
@FSmithYDH 

I believe this error might have been resolved with the latest merge to core.  Can you clean your dependencies and try it again with the master branch?  I just gave it a try on my end and I got a 200 response.

Let me know if you're still having the same issue.

Thanks

**Comment by FSmithYDH** [comment]
Hi @jonterrylee, 1.10.

I'll give that a try.

**Comment by kalihos** [comment]
Hi all.

I'm having the same problem, but I'm using FHIR server with SQL Server (not Mongo). I downloaded the whole package on 2018-10-23, so I don't think previous solution fits for me. I get this problem only when updating a patient, as it's the only moment that "path" is currently used. I realized that, when querying a patient using filters (not ID) I got a strange field: "fullUrl":"undefined/3_0_1/Patient/31773". And I wonder if that "undefined" is related to the same error or not.

Can you please help me?

Thank you in advance.

**Comment by Robert-W** [comment]
Hi @kalihos,

I'll look into that this morning and let you know what I can find. It's quite possible that the undefined is related as that absolutely shouldn't be undefined.  I'll look through the update code and see what I can find. Do you have a stack trace of the error you would be able to share?

**Comment by kalihos** [comment]
Hi @Robert-W,

Yes, of course. I get the following when updating a patient:

2019-01-16T13:48:04.024Z - error:  message=Path must be a string. Received undefined, stack=TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Object.handleUpdateResponse (C:\kalihos\node_modules\@asymmetrik\node-fhir-server-core\src\server\utils\response.utils.js:150:39)
    at service.update.then (C:\kalihos\node_modules\@asymmetrik\node-fhir-server-core\src\server\profiles\patient\patient.controller.js:157:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Thank you very much.

**Comment by Robert-W** [comment]
Thanks, I'll get back to you as soon as I have something

**Comment by Robert-W** [comment]
So without checking the older version of code, I see two potentially problematic lines of code with the current version, which is
 
```javascript
if (resource_version) {
  res.set('Content-Location', `${path.join(resourceUrl, base_version, type, id, '_history', resource_version)}`);
  res.set('ETag', `${resource_version}`);
}
```

and

```javascript
res.set('Location', `${path.join(resourceUrl, base_version, type, id)}`);
```

It looks like the resourceUrl is missing, which would be why you see this "undefined/3_0_1/Patient/31773".

Do you have a resourceUrl specified in your config, e.g.

```javascript
let fhirServerConfig = {
  auth: {
    // This servers URI
    resourceServer: env.RESOURCE_SERVER,
  }
};
```

If so, this is populated from either the env.json or defining an environment variable called `RESOURCE_SERVER` and you may need to check that it is defined.

**Comment by kalihos** [comment]
Yes! It works!!! It was exactly the problem, so it was my fault.

Thank you very much!!!
