### ISSUE TITLE
Request all patients throws 500 error

### ISSUE THREAD

**Issue by carlosa-suarez** [Asymmetrik/node-fhir-server-mongo#31]
### Are you reporting a bug?
Yes

**What is the current behavior?**
When I try to reach "http://localhost:3000/3_0_1/Patient/", it throws the next exception: "Invalid regular expression: /[object/: Unterminated character class

**What is the expected behavior?**
It might retrieve all the patients in a bundle response like some other FHIR servers
**What are the steps to reproduce?**
After starting docker-compose
1. Open postman
2. enter some sample patient like the given in the readme file
3. request app and perform a get request pointing to `http://localhost:3000/3_0_1/Patient/` 

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
Windows 10 Pro
Node v8.12.0
@asymmetrik/node-fhir-server-mongo 1.1.0
@asymmetrik/node-fhir-server-core 1.2.0
Docker version 18.06.1-ce

**Comment by jonterrylee** [comment]
Hi @carlosa-suarez 

Do you have anything in the body of your post?  There is an issue where the params is merging from both the body and the query in the request.  If you have anything in your POST body, that might cause this issue to come up.

We'll have a fix for the query/body check soon.
