### ISSUE TITLE
Using authentication on the mongo DB

### ISSUE THREAD

**Issue by sureshHARDIYA** [Asymmetrik/node-fhir-server-mongo#32]
### Do you want to request a feature, improve documentation, or ask a question?
I want to ask a question. I am new in both FHIR, SMART FHIR and health record. But, based on my recent study, it seems this has very good future. And I want to use this for my application that I am trying to make. 

### Are you reporting a bug?
No. 

I want to use authentication before someone can create Patient, or Organization. I have been reading blogs and googling and it seems the plan is to use SMART FHIR. But, I did not find any documentation explaining how can I use this. 

Sorry for very generic question but I have been strugging with this since few days and wondering to get direction. 

Regards,

Suresh

**Comment by jonterrylee** [comment]
Hi @sureshHARDIYA 

Are you having issues figuring out how to do authorization with our server or with the SMART FHIR specification?  [SMART FHIR](http://hl7.org/fhir/smart-app-launch/)?

Our server is built with the SMART on FHIR specification.  We have a scope validator that will check every request and ensure you have the right permissions before you can create/read a resource.

Tips on how to enable auth for our server:

If you have access to an Open ID server you can use our strategy.  If you don't, you can create a Basic Strategy for the time being (username/password).

Our sample strategy [OpenID Strategy](https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/strategies/bearer.strategy.js).

To enable this strategy, uncomment the configuration in the [config file](https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/config.js).

Edit your env variables to give it the properties it needs.  If you're using docker, edit the [docker-compose file](https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/docker-compose.yml)

If this is set up correctly, everything should be working.  It takes a little while to learn the spec but once you do, it's not so bad.

Let me know if you need more information (auth endpoint / token endpoint).  There's still a lot involved if you're new to this.

**Comment by sureshHARDIYA** [comment]
@jonterrylee Thank you so much for a prompt reply. Really appreciate it. 

> Are you having issues figuring out how to do authorization with our server or with the SMART FHIR specification itself?
I am having an issue figuring out how to do the authorization with [your server.](https://github.com/Asymmetrik/node-fhir-server-mongo) which is based on SMART FHIR right? So, it should include an authorization module. 

>I can walk you through this if you need help.
That would be great. 

Basically, what I am trying to do is, save all my EHR records in MongoDB, and only allow CREATE/READ/UPDATE/DELETE by authorized users.  With this server, I could run and CREATE patient based on the documentation but I do not seem to have an authentication built in this process. I am new to SMART FHIR concept. Which seems difficult to grasp at once. Traditionally, I am used to a client-server architecture where a client communicates with the server using REST API. I am trying to find how SMART fits into this architecture. I saw the diagrams on SMART FHIR, to be honest, but it seems quite abstract to me.

**Comment by Zandahr** [comment]
I would love a walk-trough with how to set the server to accept username and password authentication for the time being, so that I can run simple tests without having to use an external authentication server.

**Comment by Robert-W** [comment]
Thanks for the reminder @Zandahr, we have an open issue on core for this exact thing. We have recently published the core server module as an npm module and have been working on cleanup and adding new features. I tried disabling the authentication this morning and it is pretty straight forward. You should be able to just comment out the strategy in the config so if you are just running simple tests, this may be the easiest.

In `src/config.js`, look for something similar to the following and comment out the entire strategy block:

```javascript
let fhirServerConfig = {
  auth: {
    // Comment out this entire strategy block
    strategy: {
      ....
    }
  },
  ....
};
```

I'll talk to Jon this morning and see how soon we can add an example to our documentation, so that we can show how to incorporate your own passport strategy into the project.  We set it up so you can provide your own strategy, but after reviewing the Wiki this morning, realize the docs are very stale.

We also plan on doing a refresh of this repo once we get the core server's next version released (1.3.1 should be released this week and hopefully I can update this as well by the end of the week).

**Comment by jeetendra-choudhary** [comment]
@sureshHARDIYA Did you get a solution to this? If yes can you please share the sample please.
@Zandahr Request your help to get a basic sample of authentication using bearer token and basic username password.

**Comment by sshah-asymmetrik** [comment]
@jeetendra-choudhary I believe this discussion led to the creation of this `node-fhir-server-core` wiki page on Access Control (https://github.com/Asymmetrik/node-fhir-server-core/wiki/Access-Control). This should help you with defining an SOF bearer strategy.
