### ISSUE TITLE
AllergyIntolerance records are not stored 

### ISSUE THREAD

**Issue by carlosa-suarez** [Asymmetrik/node-fhir-server-mongo#33]
### Do you want to request a feature, improve documentation, or ask a question?
How can I see the stored records after inserting an allergy resource
### Are you reporting a bug?
yes
**What is the current behavior?**
After creating a new allergy intolerance, the record is not present
**What is the expected behavior?**
The record should appear by searching all the allergy intolerance or by Id
**What are the steps to reproduce?**
1. insert an allergy intolerance using the next data using methods PUT or POST
url: `http://localhost:3000/3_0_1/allergyintolerance/1d9nd7a9ajo`
`{
    "resourceType": "AllergyIntolerance",
    "id": "1d9nd7a9ajo",
    "clinicalStatus": "active",
    "type": "allergy",
    "category": [
        "medication"
    ],
    "criticality": "low",
    "code": {
        "coding": [
            {
                "system": "RxNorm",
                "code": "7980"
            }
        ],
        "text": "Penicillin G"
    },
    "patient": {
        "id": "6867144748"
    }
}`
It throws 200 (using PUT), or 201 (using POST)
2. but when I try to get `http://localhost:3000/3_0_1/allergyintolerance` without sending any body info
It just shows a default sample record
3. and when I try to get ` http://localhost:3000/3_0_1/allergyintolerance/1d9nd7a9ajo` the record doesn't exist
**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
Windows 10 Pro
Node v8.12.0
@asymmetrik/node-fhir-server-mongo 1.1.0
@asymmetrik/node-fhir-server-core 1.2.0
Docker version 18.06.1-ce

**Comment by jonterrylee** [comment]
Hi @carlosa-suarez 

This is just an example repo with only the patient and organization service built out.  There is a [PR](https://github.com/Asymmetrik/node-fhir-server-mongo/pull/34) for allergy intolerance thanks to FSmithYDH.  This Repo is mainly to show how you connect the core lib to a backend.

**Comment by carlosa-suarez** [comment]
Thanks @jonterrylee ,

I'll follow the same schema that @FSmithYDH followed to create valueset resources.

Closing this issue.
