### ISSUE TITLE
Create patient example on readme returns an error

### ISSUE THREAD

**Issue by romgrk** [Asymmetrik/node-fhir-server-mongo#36]
### Do you want to request a feature, improve documentation, or ask a question?
Improve doc/ask question

### Are you reporting a bug?
Don't know

**What is the current behavior?**
I followed the example to create a patient that is on the readme. It didn't work, received the following error:
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td><pre>'resourceType' expected to have value of 'Patient', received 'undefined'</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "'resourceType' expected to have value of 'Patient', received 'undefined'"
        }
    ]
}
```

**What is the expected behavior?**
The doc explains how to make it work.

**What are the steps to reproduce?**
 - clone the project
 - `docker-compose up`, see the `verbose: Server is up and running!` message
 - send a request with the config below

![screenshot from 2018-12-19 17-35-17](https://user-images.githubusercontent.com/1423607/50252328-a8a6a180-03b4-11e9-95eb-ce8008ee510d.png)

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
node: 10.8.0
OS: ubuntu 18.04
node-fihr-server-mongo: master (fecdd7e)

**Comment by Robert-W** [comment]
Hi @romgrk,

thanks for reporting this. @jonterrylee and myself have been cleaning up PR's on the core library this is based on this week and are working on getting to these issues soon. What you are doing looks correct so this may be a bug. We'll try to figure out what is going on today and let you know when we can get a fix.

The core library is hopefully going to get published to npm today with many bug fixes. Once this happens, we are going to point this repo to that instead of the latest code on master (all our patches are in a develop branch at the moment), so this may fix your issue

**Comment by jonterrylee** [comment]
@romgrk 

Theres 2 things that may be causing this issue.  Did you set your contextType to 'application/json+fhir' or 'application/fhir+json?  If you didn't, the body will not get passed through.

If you did, then Postman does this flaky thing where it sends the body as a string.  Try this...

In Postman:
 1.  Change body raw type from 'Text' to 'JSON'.  This will change the contextType to 'application/json'
 2.  Under Headers - change the contextType back to 'application/json+fhir'.  This will change the body type back to Text.
3.  Run the request again and see if that works.

**Comment by romgrk** [comment]
@jonterrylee I've included the `application/fihr+json` content-type:

![screenshot from 2018-12-20 14-02-24](https://user-images.githubusercontent.com/1423607/50305128-fd532680-045f-11e9-93a4-ced14b3569d5.png)

@Robert-W Got it :)

**Comment by jonterrylee** [comment]
@romgrk 

You spelled 'fhir' wrong.  It needs to be 'application/fhir+json' =)

Hopefully that solves your issue

**Comment by romgrk** [comment]
@jonterrylee indeed, I've been writing it wrong everywhere :/ Issue solved
