### ISSUE TITLE
Getting started help

### ISSUE THREAD

**Issue by mthakershi** [Asymmetrik/node-fhir-server-mongo#39]
Hello, I am a beginner with FHIR. I have my patient database in SQL server. I would like to expose certain FHIR resources (patient, ADT messages, care plan, observations) to vendors with proper authentication and authorization. Can I achieve that with Asymmetrik FHIR server? How should I proceed?

Thanks for guidance.

**Comment by Robert-W** [comment]
Hi @mthakershi, sorry for the late reply.  I've been a little swamped with the core repo, graphql, and some of our enterprise related options lately.

Yes you can. We have a much more comprehensive repo at [https://github.com/Asymmetrik/node-fhir-server-core](https://github.com/Asymmetrik/node-fhir-server-core). It has a nice getting started guide that talks about setting up a simple FHIR server. It also has support for SMART on FHIR out of the box with the ability to add your own authentication/authorization if needed. The core repo exposes a plugin system where you can plugin your own services and that is where you can connect to your own data sources. If Node.js supports then you can use it, we do not place any limitations on what you can use.  If you need any help with that than feel free to open issues/questions on that repo. Asymmetrik will also have enterprise solutions available very soon which will have a lot more capabilities than what is available in the open source versions of our servers.
