### ISSUE TITLE
How to use a custom profile?

### ISSUE THREAD

**Issue by s0d-d** [Asymmetrik/node-fhir-server-mongo#44]
### Do you want to request a feature, improve documentation, or ask a question?
Asking a question

### Are you reporting a bug?
No.

**What OS are you using and what version of node.js and @asymmetrik/fhir-server-core are you running?**
I am using Ubuntu 16.04, v10.15 of NodeJS, and v2.0 of @asymmetrik/node-fhir-server-core.

------------------------------------------------------------------------------------------------------------------
Hello, 

I am new to NodeJS and am having trouble creating a custom profile. 

I find that in the 'node-fhir-server-core' there is standards folder containing profile classes, so I cloned core server code locally and changed the dependency from:     
`"@asymmetrik/node-fhir-server-core": "git+https://github.com/Asymmetrik/node-fhir-server-core.git"`
to:   
`"@asymmetrik/node-fhir-server-core": "/home/user/node-fhir-server-core"`

And then added a dummy element to the Patient class like this: 
```
// Whether this patient record is in active use.
	get my_active() {
		return this.__my_active;
	}

	set my_active(new_value) {
		this.__my_active = new_value;
	}
```
But the new element is not saved when create request is received.
I guess I should update the module and use it, but I don't know how. 
Could anyone tell me how to do this?

Am I changing the structure of default Patient Resource?

If so, How can I import custom profile and check validation with that profile?

**Comment by s0d-d** [comment]
Am I changing the structure of default Patient Resource?

If so, How can I import custom profile and check validation with that profile?

**Comment by icj217** [comment]
I have a similar question as OP. It would be helpful for the documentation to explicitly mention how to implement custom profiles that modify/build on top of the base resources.

**Comment by sshah-asymmetrik** [comment]
Hey guys,

Great question! If you're looking for how to make local customizations to resources in `node-fhir-server-core` and have the behavior reflect when you run `node-fhir-server-mongo`, I put together this page to guide you through the steps:
https://github.com/Asymmetrik/node-fhir-server-mongo/wiki/Customizing-node-fhir-server-core-Behavior

If you'd like to implement a new profile using a structure definition and have your resources validated against that, contact us at fhir-dev@asymmetrik.com and let us know more about your use case! While adding a custom profile through the core API is not currently an option, we may still be able to help you address your needs.

Let us know if you have other questions! Thanks!

**Comment by viniciuspetrol** [comment]
I need to add new profile defined called [Individuo](https://simplifier.net/RedeNacionaldeDadosemSade/BRIndividuo/~overview).

I get this message while running the server.

UnhandledPromiseRejectionWarning: Error: Individuo is an invalid profile configuration, please see the wiki for instructions on how to enable a profile in your server, https://github.com/Asymmetrik/node-fhir-server-core/wiki/Profile

Is there a way to prevent it? Or it is impossible to create a whole new Resource?

**Comment by luan-dev** [comment]
Adding custom profiles is currently not supported on `node-fhir-server-core`
