### ISSUE TITLE
_history page

### ISSUE THREAD

**Issue by benapra** [Asymmetrik/node-fhir-server-mongo#48]
### Are you reporting a bug?

**What is the current behavior?**

Accessing `http://localhost:3000/3_0_1/Patient/hhPTufqen3Qp-997382` works as expected, but here is the issue.

When Updating the information about a patient, I get the following:
`error:  message=E11000 duplicate key error collection: fhir.Patient_3_0_1_History index: _id_ dup key: { : "hhPTufqen3Qp-997382" }, stack=MongoError: E11000 duplicate key error collection: fhir.Patient_3_0_1_History index: _id_ dup key: { : "hhPTufqen3Qp-997382" }`

And then, when accessing `/3_0_1/Patient/hhPTufqen3Qp-997382/_history`, I can't see the whole history of the patient I updated.

I think the issue lies here:
`let history_patient = Object.assign(cleaned, { id: id });`

history_patient actually ends up containing the `_id`, which causes the database error.

**What is the expected behavior?**

I want to be able to see complete history of a patient.

**What are the steps to reproduce?**

Create a patient.
Update them once -> this works fine, since the `Patient_3_0_1_History` only contains one row for that patient
Update them again -> get the error I mentioned, and see that `Patient_3_0_1_History` does not contain the full history of the patient.

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
node: v10.15.3
@asymmetrik/node-fhir-server-core: 1.4

**Comment by jonterrylee** [comment]
Thanks @benapra 

This should have been fixed but we will verify the issue.
