### ISSUE TITLE
What's the significance of stringifying and re-parsing resource object before inserting into DB in patient.service.js? 

### ISSUE THREAD

**Issue by navndn** [Asymmetrik/node-fhir-server-mongo#49]
### Do you want to request a feature, improve documentation, or ask a question?
This is a question! (maybe a silly one)

As mentioned in the title, I'm wondering what's the significance of this line in patient.service.js here..

https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/services/patient/patient.service.js#L491

Thanks!

**Comment by jonterrylee** [comment]
@navndn 

We did to coerce the record into a FHIR type and stringify + parse to remove the nulls/undefined.  This could be done in other ways.  We are also contemplating on saving the record as is (raw) and coerce it on read.  But this is strictly up to you.
