### ISSUE TITLE
Trying to use the fhir server

### ISSUE THREAD

**Issue by sychus** [Asymmetrik/node-fhir-server-mongo#50]
### Do you want to request a feature, improve documentation, or ask a question?
question
### Are you reporting a bug?
Nop
**What is the current behavior?**
I am following the instructions but I can not get it to work and I am receiving the following error:
Error 500
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "internal",
            "details": {
                "text": "Unexpected: Cannot read property 'info' of undefined"
            }
        }
    ]
}
**What is the expected behavior?**
expect 200 and insert a patient from the example.
**What are the steps to reproduce?**

0) npm start (the server is up and running correctly)
1) Open postman
2) PUT verb
3) In headers set:
Content-Type :application/fhir+json
Cache-Control: no-cache
4) In body, I set a Patient from example.
**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
OS: 
**Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia**
Node version: **v10.4.1**
@asymmetrik/node-fhir-server-mongo:  **version: 1.2.0**
Mongodb version: 
**db version v4.0.9
git version: fc525e2d9b0e4bceff5c2201457e564362909765
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1404
    distarch: x86_64
    target_arch: x86_64**

Thank you in advance!!
Hugo

**Comment by jonterrylee** [comment]
@sychus 

I updated the example to work with the Core lib 2.x.  

Take a look at this branch and let me know if this doesn't work.
[branch](https://github.com/Asymmetrik/node-fhir-server-mongo/tree/feature/v2)

**Comment by sychus** [comment]
@jonterrylee It works perfect!!! Thank you very much!
