### ISSUE TITLE
POSTing to the root (Transaction/Bundle)

### ISSUE THREAD

**Issue by IsaacRay** [Asymmetrik/node-fhir-server-mongo#52]
### Do you want to request a feature, improve documentation, or ask a question?
Ask a question

### Are you reporting a bug?
No

**What is the current behavior?**

Trying to POST a transaction Bundle to the root, keep getting a OperationOutcome - > "Invalid URL : /"

Question is simply, does this implementation have the capacity to POST transaction Bundles to the root url? Is this something I need to enable somehow? If so, is there documentation on how to do so?

**What is the expected behavior?**

**What are the steps to reproduce?**

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**

**Comment by sshah-asymmetrik** [comment]
Hi Isaac,

The short answer is that batch/transaction behavior is not currently supported in this implementation.  

The reason that you're getting an "Invalid URL" is that there is no express route for the root location in the current release of `node-fhir-server-core`, which this implementation is built upon.

According to the FHIR spec, batch and transaction operations are 2 different things, where batch is treated as a bunch of independent operations that succeed/fail independently and a transaction is one big bulk operation that either completely succeeds/fails. Supporting transactions on mongo may be a bit trickier, as it will involve using replica sets. However, supporting batches is more straightforward.

To add support for batch operations, we would need to add base/root routes and controllers to `node-fhir-server-core` and then a batch service here in `node-fhir-server-mongo`. We'll add it to our backlog, but feel free to add it in yourself if time is of the essence!

Thanks,
Sumeet

**Comment by sshah-asymmetrik** [comment]
Hi Isaac,

Just an update on this, I've done some work on supporting batch operations. While I still need to write out the unit tests and whatnot before merging in, the support for batch operations has been added to `node-fhir-server-core`. Changes to `node-fhir-server-mongo` are not actually necessary to support batch operations.

These changes will propagate into master and the main branch once they have been fully tested and reviewed. Until then, the changes can be seen in the PR at https://github.com/Asymmetrik/node-fhir-server-core/pull/184.

Thanks,
Sumeet

**Comment by sychus** [comment]
Hi shah,
I was seeing the functionality you added in the PR Asymmetrik / node-fhir-server-core # 184. The problem I notice is that you are only allowing POST in its implementation. Then it occurs to me that we could make the following modification:
```javascript
let routes = [{
    type: 'put',
    path: '/: base_version /',
    corsOptions: {
        methods: ['PUT'],
    },
    args: [],
    controller: controller.batch
},
{
    type: 'post',
    path: '/: base_version /',
    corsOptions: {
        methods: ['POST'],
    },
    args: [],
    controller: controller.batch
},
{
.... et cetera
}
];
```
Then in the route.js make the following change within setRoutes:
``` javascript
function setRoutes(options = {}) {
	let { app, config } = options;
	let { server } = config;
	let { routes } = require('./base/base.config');
	let corsDefaults = Object.assign({}, server.corsOptions);
	enableMetadataRoute(app, config, corsDefaults);
	enableResourceRoutes(app, config, corsDefaults);
	routes.forEach(route => enableBaseRoute(route, app, config, corsDefaults));
}
```
Do you think it's right?
Finally, could I follow the same logic to load routes for bundle transactions? 

On the other hand, what is the idea of ​​the bundle.js service in Asymmetrik / node-fhir-server-mongo how could I implement it?

Thank you very much!
Best regards

Hugo

**Comment by luan-dev** [comment]
Closing stale request. Please comment if this is still relevant
