### ISSUE TITLE
Issue for a new resource implementation - Immunization

### ISSUE THREAD

**Issue by Yani06** [Asymmetrik/node-fhir-server-mongo#64]
### Do you want to request a feature, improve documentation, or ask a question?
I try to add a new Immunization resource that is explained on your official documentation.
**Immunization**  resource is inpired on : **Patient** and **Organization** implementation.

### Are you reporting a bug?
I have this kind of error  in:  create or update method on immunization.service file

**What is the current behavior?**

{"message":{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"internal","details":{"text":"Unexpected: Cannot read property 'info' of undefined"}}]},"level":"error"}

**What is the expected behavior?**

**What are the steps to reproduce?**

**profiles config:**  

> profiles: {
		Immunization: {
			service: './src/services/immunization/immunization.service.js',
			versions: [ VERSIONS['4_0_0'],VERSIONS['3_0_1'], VERSIONS['1_0_2'] ]
		},
		AllergyIntolerance: {
			service: './src/services/allergyintolerance/allergyintolerance.service.js',
			versions: [ VERSIONS['4_0_0'] ]
		},
		Organization: {
			service: './src/services/organization/organization.service.js',
			versions: [ VERSIONS['4_0_0'] ]
		},
		Patient: {
			service: './src/services/patient/patient.service.js',
			versions: [ VERSIONS['4_0_0'] ]
		}		
	}

**immunization service:**
`module.exports.update = (args, {req}) => new Promise((resolve, reject) => {
logger.info('Immunization >>> update');

	let resource = req.body;
	let { base_version } = args;

	let db = globals.get(CLIENT_DB);
	let collection = db.collection(`${COLLECTION.IMMUNIZATION}_${base_version}`);

	let Immunization = getImmunization(base_version);
	// Cast resource to Immunization Class
	let immunization_resource = new Immunization(resource);

	let id = getUuid(immunization_resource);
	let Meta = getMeta(base_version);	
	immunization_resource.meta = new Meta({ versionId: '1', lastUpdated: moment.utc().format('YYYY-MM-DDTHH:mm:ssZ') });

	let doc = JSON.parse(JSON.stringify(immunization_resource.toJSON()));
	Object.assign(doc, { id: id });
	let history_doc = Object.assign({}, doc);
	Object.assign(doc, { _id: id });

	// Insert our organization record
	collection.insertOne(doc, (err) => {
		if (err) {
			logger.error('Error with Immunization.create: ', err);
			return reject(err);
		}

		let history_collection = db.collection(`${COLLECTION.IMMUNIZATION}_${base_version}_History`);

		// Insert our organization record to history but don't assign _id
		return history_collection.insertOne(history_doc, (err2) => {
			if (err2) {
				logger.error('Error with ImmunizationHistory.create: ', err2);
				return reject(err2);
			}
			return resolve({ id: doc.id, resource_version: doc.meta.versionId });
		});
	});
`

**PUT** : http://localhost:3000/4_0_0/Immunization/1

**Body**:  ` {
  "resourceType": "Immunization",
  "id": "1",
  "text": {
    "status": "generated",
    "div": ""
  },
  "identifier": [
    {
      "system": "urn:ietf:rfc:3986",
      "value": "urn:oid:1.3.6.1.4.1.21367.2005.3.7.1234"
    }
  ],
  "status": "completed",
  "vaccineCode": {
    "coding": [
      {
        "system": "urn:oid:1.2.36.1.2001.1005.17",
        "code": "FLUVAX"
      }
    ],
    "text": "Fluvax (Influenza)"
  },
  "patient": {
    "reference": "Patient/example"
  },
  "encounter": {
    "reference": "Encounter/example"
  },
  "occurrenceDateTime": "2013-01-10",
  "primarySource": true,
  "location": {
    "reference": "Location/1"
  },
  "manufacturer": {
    "reference": "Organization/hl7"
  },
  "lotNumber": "AAJN11K",
  "expirationDate": "2015-02-15",
  "site": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActSite",
        "code": "LA",
        "display": "left arm"
      }
    ]
  },
  "route": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/v3-RouteOfAdministration",
        "code": "IM",
        "display": "Injection, intramuscular"
      }
    ]
  },
  "doseQuantity": {
    "value": 5,
    "system": "http://unitsofmeasure.org",
    "code": "mg"
  },
  "performer": [
    {
      "function": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0443",
            "code": "OP"
          }
        ]
      },
      "actor": {
        "reference": "Practitioner/example"
      }
    },
    {
      "function": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0443",
            "code": "AP"
          }
        ]
      },
      "actor": {
        "reference": "Practitioner/example"
      }
    }
  ],
  "note": [
    {
      "text": "Notes on adminstration of vaccine"
    }
  ],
  "reasonCode": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "429060002"
        }
      ]
    }
  ],
  "isSubpotent": true,
  "education": [
    {
      "documentType": "253088698300010311120702",
      "publicationDate": "2012-07-02",
      "presentationDate": "2013-01-10"
    }
  ],
  "programEligibility": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/immunization-program-eligibility",
          "code": "ineligible"
        }
      ]
    }
  ],
  "fundingSource": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/immunization-funding-source",
        "code": "private"
      }
    ]
  }
}`

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**

node: 12.16.2
package.json :
 "dependencies": {
    "@asymmetrik/node-fhir-server-core": "2.0.7",
    "fast-json-patch": "^2.0.7",
    "moment-timezone": "^0.5.14",
    "mongo": "^0.1.0",
    "object-hash": "^1.3.1",
    "var": "^0.3.2"
  },

**Comment by zeevosec** [comment]
Hi there!

Do you have a fork where this change is made anywhere?

**Comment by Yani06** [comment]
Hi @zeevosec 
I pushed a version here :
https://github.com/Yani06/fhir-mongo

Thanks

**Comment by zeevosec** [comment]
@Yani06 Thanks for sharing. You have uncovered that a lot of services in node-fhir-server-mongo have not been migrated to be compatible with node-fhir-server-core@2.0.0. More here:

https://github.com/Asymmetrik/node-fhir-server-core/blob/master/docs/MIGRATION_2.0.0.md#logging

I have raised issue #65, assigned myself, and will be working to migrate all resources including Immunization to be compatible with node-fhir-server-core >2.0.0

**Comment by zeevosec** [comment]
@Yani06 Issue #65 (now resolved) may have fixed your issue. See how Immunization works now and compare it with your fork. Let me know if you have any other problems.

THanks!

**Comment by Yani06** [comment]
@zeevosec  Thank a lot for you help !

Is it an oversight  for organization service  ?
https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/services/organization/organization.service.js

**Comment by zeevosec** [comment]
@Yani06 PR #70 May have fixed your issue
