### ISSUE TITLE
Not able to create Organization resource

### ISSUE THREAD

**Issue by rchinthakuntla** [Asymmetrik/node-fhir-server-mongo#75]
### Are you reporting a bug?
Possibly! 

**What is the current behavior?**
I am able to invoke the endpoint to create new organization resource.  My postman is returning 201 OK created response. 
But when I look into the collection within MongoDB, I cannot see any organization objects. The collection is empty.  

**What is the expected behavior?**
When the FHIR server returns 201 created response, I should be able to see the resource in MongoDB collection. 

**What are the steps to reproduce?**

Post the following payload to FHIR server 

HTTP Method: POST
Content-Type: application/fhir+json

{
    "resourceType": "Organization",
    "id": "21ffe804-e8ee-4ca9-b177-752e75bd5631",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2018-05-30T23:52:00.811+00:00",
        "tag": [
            {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea"
            }
        ]
    },
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "2d3c549c-f4e7-48aa-acb0-0fe7bbe7b467"
        }
    ],
    "type": [
        {
            "coding": [
                {
                    "system": "Healthcare Provider",
                    "code": "prov",
                    "display": "Healthcare Provider"
                }
            ],
            "text": "Healthcare Provider"
        }
    ],
    "name": "SHRINERS' HOSPITAL FOR CHILDREN - BOSTON, THE",
    "telecom": [
        {
            "system": "phone",
            "value": "6177223000"
        }
    ],
    "address": [
        {
            "line": [
                "51 BLOSSOM STREET"
            ],
            "city": "BOSTON",
            "state": "MA",
            "postalCode": "02114",
            "country": "US"
        }
    ]
}

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**

I am running on Windows 10 professional OS, using latest version of Node JS and node-fhir-server-mongo (current release).

**Comment by sychus** [comment]
Hi @rchinthakuntla

When I started studying asymmetrik implementations I did some testing with this fhir resource. Here is an example (not ):
https://github.com/andes/node-fhir-server-mongo/blob/master/src/services/organization/organization.service.js

I'm now working on a facade implementation that better corresponds to my current needs.
https://github.com/sychus/fhir-facadeServer-andes

I love Asymmetrik projects!! tell me if you need some help!
