### ISSUE TITLE
Error: AllergyIntolerance is an invalid profile configuration

### ISSUE THREAD

**Issue by bRRRITSCOLD** [Asymmetrik/node-fhir-server-mongo#80]
### Do you want to request a feature, improve documentation, or ask a question?
Question

### Are you reporting a bug?
yes

**What is the current behavior?**
Error on start up after clone and npm install.

Error: AllergyIntolerance is an invalid profile configuration, please see the wiki for instructions on how to enable a profile in your server, https://github.com/Asymmetrik/node-fhir-server-core/wiki/Profile

**What is the expected behavior?**
To start without issue after clone and npm install

**What are the steps to reproduce?**
(Assuming local mongo is already running)
1) git clone
2) npm install

**What OS are you using and what version of node.js, @asymmetrik/node-fhir-server-core, and @asymmetrik/node-fhir-server-mongo are you running?**
Windows 10 and OSx Catalina, ^2.0.4, 2.0.0

**Comment by zeevosec** [comment]
I'll be looking at this today. Thanks.

**Comment by bRRRITSCOLD** [comment]
@zeevosec If you need anything lmk. Always willing to help and provide information.

**Comment by bRRRITSCOLD** [comment]
@zeevosec Saw your PR in fhir-node-server-core. I will report back once I can retry this later today. I will close if fixed.

Thank you so much!

**Comment by zeevosec** [comment]
@bRRRITSCOLD I don't think we are there yet but I will be fixing this today. Been swamped lately!

**Comment by bRRRITSCOLD** [comment]
@zeevosec Do not even mention it, I know the feeling myself... this whole week -_- lol. Next week should clear up for me at work, freeing me up for side stuff.

If you have a particular branch you are working off of besides the main lmk. I can jump in with you over the weekend/next week and work through the triaging/debugging if needed.

FHIR is pretty new to me, but Node certainly isnt :)

**Comment by zeevosec** [comment]
@bRRRITSCOLD I updated `core` and upgraded this project's package.json. It seems to be working now. Thanks for raising this issue!
