### ISSUE TITLE
posted data not being written to DB

### ISSUE THREAD

**Issue by noktilux** [Asymmetrik/node-fhir-server-mongo#98]
### Are you reporting a bug?
I believe so.

**What is the current behavior?**
Using your very own data example and variations on it, posted data does not save.  A patient entry is created in MongoDB, but only contains the following...

> use fhir
switched to db fhir
> db.Patient_4_0_0.find()
{
    "_id" : "555",
    "id" : "555",
    "resourceType" : "Patient",
    "meta" : {
        "versionId" : "1",
        "lastUpdated" : "2021-06-11T14:00:49+00:00"
    }
}

**What is the expected behavior?**

That all of the data posted would be saved.

**What are the steps to reproduce?**

Create a json file (for example test-data.json) containing the example data you present in documentation.  Then run this command:

curl -X PUT "http://localhost:3000/4_0_0/Patient/555" -H "application/fhir+json" --data "@test-data.json"

I am using Ubuntu 18.04 as operating system.
@asymmetrik/node-fhir-server-mongo, version 2.0.0

**Comment by bsai** [comment]
Make sure below header should be in place.
**Content-Type: application/fhir+json**
